word = input("Hi, type in a word and I will tell you if it is a palindrome: ")
letters_in_word = list(word)
letters_in_word.reverse()
string_from_list = "".join(letters_in_word)
print(f'Your word is a palindrome: {string_from_list == word}')